#! /bin/sh
RUN="time ./fillit"
SRCS="./eval_tests/"

${RUN} ${SRCS}failure_000_disjoint_piece.txt
${RUN} ${SRCS}failure_001_empty.txt
${RUN} ${SRCS}failure_002_newline_only.txt
${RUN} ${SRCS}failure_003_27_pieces.txt
${RUN} ${SRCS}failure_004_trailing_newline.txt
${RUN} ${SRCS}failure_005_extraneous_newline.txt
${RUN} ${SRCS}failure_006_missing_separating_newline.txt
${RUN} ${SRCS}failure_007_missing_terminating_newline.txt
${RUN} ${SRCS}failure_008_missing_piece_line.txt
${RUN} ${SRCS}failure_009_extraneous_piece_line.txt
${RUN} ${SRCS}failure_010_extraneous_piece_square.txt
${RUN} ${SRCS}failure_011_missing_piece_square.txt
${RUN} ${SRCS}failure_012_missing_character_piece_line.txt
${RUN} ${SRCS}failure_013_extraneous_character_piece_line.txt
${RUN} ${SRCS}failure_014_illegal_character.txt
${RUN} ${SRCS}failure_015_diagonal_square_alignment.txt
${RUN} ${SRCS}success_000.txt
${RUN} ${SRCS}success_001.txt
${RUN} ${SRCS}success_002.txt
${RUN} ${SRCS}success_003.txt
${RUN} ${SRCS}success_004.txt
${RUN} ${SRCS}success_005.txt
${RUN} ${SRCS}success_006.txt
${RUN} ${SRCS}success_007.txt
${RUN} ${SRCS}success_008.txt
${RUN} ${SRCS}success_009.txt
${RUN} ${SRCS}success_010.txt
${RUN} ${SRCS}success_011.txt
${RUN} ${SRCS}success_012.txt
${RUN} ${SRCS}success_013.txt
${RUN} ${SRCS}success_014.txt
${RUN} ${SRCS}success_015.txt
${RUN} ${SRCS}success_016.txt
${RUN} ${SRCS}success_017.txt
${RUN} ${SRCS}success_018.txt
${RUN} ${SRCS}success_019.txt
${RUN} ${SRCS}success_020.txt
${RUN} ${SRCS}success_021.txt
${RUN} ${SRCS}success_022.txt
${RUN} ${SRCS}success_023.txt
${RUN} ${SRCS}success_024.txt
${RUN} ${SRCS}success_025.txt
${RUN} ${SRCS}success_026.txt
${RUN} ${SRCS}success_027.txt
${RUN} ${SRCS}success_028.txt
${RUN} ${SRCS}success_03_01_pieces_rand.txt
${RUN} ${SRCS}success_03_02_pieces_rand.txt
${RUN} ${SRCS}success_03_03_pieces_rand.txt
${RUN} ${SRCS}success_03_04_pieces_rand.txt
${RUN} ${SRCS}success_03_05_pieces_rand.txt
${RUN} ${SRCS}success_03_06_pieces_rand.txt
${RUN} ${SRCS}success_03_07_pieces_rand.txt
${RUN} ${SRCS}success_03_08_pieces_rand.txt
${RUN} ${SRCS}success_03_09_pieces_rand.txt
${RUN} ${SRCS}success_03_10_pieces_rand.txt
${RUN} ${SRCS}success_03_11_pieces_rand.txt
${RUN} ${SRCS}success_03_12_pieces_rand.txt
${RUN} ${SRCS}success_03_13_pieces_rand.txt
${RUN} ${SRCS}success_03_14_pieces_rand.txt
${RUN} ${SRCS}success_03_15_pieces_rand.txt
${RUN} ${SRCS}success_03_16_pieces_rand.txt
${RUN} ${SRCS}success_03_17_pieces_rand.txt
${RUN} ${SRCS}success_03_18_pieces_rand.txt
${RUN} ${SRCS}success_03_19_pieces_rand.txt
${RUN} ${SRCS}success_03_20_pieces_rand.txt
${RUN} ${SRCS}success_03_21_pieces_rand.txt
${RUN} ${SRCS}success_03_22_pieces_rand.txt
${RUN} ${SRCS}success_03_23_pieces_rand.txt
${RUN} ${SRCS}success_03_24_pieces_rand.txt
${RUN} ${SRCS}success_03_25_pieces_rand.txt
${RUN} ${SRCS}success_03_26_pieces_rand.txt
${RUN} ${SRCS}success_04_allshapes.txt
